### ISSUE TITLE
Got  error on populate_db.py

### ISSUE THREAD

**Issue by tshrinivasan** [Dineshkarthik/OSM-Translate-TelegramBot#1]
python populate_db.py 
Traceback (most recent call last):
  File "populate_db.py", line 19, in <module>
    df.to_sql("translation", db, if_exists="append")
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/generic.py", line 1201, in to_sql
    chunksize=chunksize, dtype=dtype)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/sql.py", line 470, in to_sql
    chunksize=chunksize, dtype=dtype)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/sql.py", line 1148, in to_sql
    table.insert(chunksize)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/sql.py", line 664, in insert
    self._execute_insert(conn, keys, chunk_iter)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/sql.py", line 639, in _execute_insert
    conn.execute(self.insert_statement(), data)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1159, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 466, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table translation has no column named node [SQL: u'INSERT INTO translation ("index", node, english, tamil, verified) VALUES (?, ?, ?, ?, ?)'] [parameters: ((1, 30143567, u'Kadapakkam', u'\u0b95\u0b9f\u0baa\u0bcd\u0baa\u0b95\u0bcd\u0b95\u0bae\u0bcd', 0), (2, 30153425, u'Chellampatty', u'Chellampatty', 0), (3, 243059957, u'Gopalapuram', u'\u0b95\u0bc7\u0bbe\u0baa\u0bbe\u0bb2\u0baa\u0bc1\u0bb0\u0ba4\u0bcd\u0ba4\u0bbf\u0bb2\u0bcd', 0), (4, 243060007, u'\u0ba8\u0ba8\u0bcd\u0ba4\u0ba9\u0bae\u0bcd', u'\u0ba8\u0ba8\u0bcd\u0ba4\u0ba9\u0bae\u0bcd', 0), (5, 243060039, u'Raja Annamalai Puram', u'\u0bb0\u0bbe\u0b9c\u0bbe \u0b85\u0ba3\u0bcd\u0ba3\u0bbe\u0bae\u0bb2\u0bc8 \u0baa\u0bc1\u0bb0\u0bae\u0bcd', 0), (6, 243060101, u'Abhiramapuram', u'Abhiramapuram', 0), (7, 243060531, u'CIT Colony', u'CIT \u0baf\u0bbf\u0bb2\u0bcd \u0b95\u0bbe\u0bb2\u0ba9\u0bbf', 0), (8, 243327628, u'Sriperumbudur', u'\u0bb8\u0bcd\u0bb0\u0bc0\u0baa\u0bc6\u0bb0\u0bc1\u0bae\u0bcd\u0baa\u0bc1\u0ba4\u0bc2\u0bb0\u0bcd', 0)  ... displaying 10 of 2794 total bound parameter sets ...  (2793, 4426284856, u'Vaishnavi Nagar', u'\u0bb5\u0bc8\u0bb7\u0bcd\u0ba3\u0bb5\u0bbf \u0ba8\u0b95\u0bb0\u0bcd', 0), (2794, 3600096905, u'Tamil Nadu', None, 0))]
[osm-strings.csv.txt](https://github.com/Dineshkarthik/OSM-Translate-TelegramBot/files/1367048/osm-strings.csv.txt)

note: 
changed lineno 19 of populate_db.py as
df = pd.read_csv(config["input_csv"],encoding='utf-8')

to solve unicode error I got.

**Comment by Dineshkarthik** [comment]
Try with python 3 ji

**Comment by Dineshkarthik** [comment]
The column names should be `osm_id,name,translation`
Please refer to readme
