### ISSUE TITLE
got error on verify

### ISSUE THREAD

**Issue by tshrinivasan** [Dineshkarthik/OSM-Translate-TelegramBot#10]
telegram@ip-172-31-29-250:~/OSM-Translate-TelegramBot$ python3 translate_bot.py 
2017-10-13 20:11:11,309 (util.py:64 WorkerThread1) ERROR - TeleBot: "AttributeError occurred, args=("'NoneType' object has no attribute 'v_index'",)
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "translate_bot.py", line 148, in get_verified
    Data.index > user.v_index,
AttributeError: 'NoneType' object has no attribute 'v_index'
"
Traceback (most recent call last):
  File "translate_bot.py", line 247, in <module>
    bot.polling(none_stop=True)
  File "/usr/local/lib/python3.4/dist-packages/telebot/__init__.py", line 264, in polling
    self.__threaded_polling(none_stop, interval, timeout)
  File "/usr/local/lib/python3.4/dist-packages/telebot/__init__.py", line 288, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "/usr/local/lib/python3.4/dist-packages/telebot/util.py", line 107, in raise_exceptions
    six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
  File "/usr/local/lib/python3.4/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "translate_bot.py", line 148, in get_verified
    Data.index > user.v_index,
AttributeError: 'NoneType' object has no attribute 'v_index'

Updated to the latest code today.

Got the above error while clicking verify.

Please check.

**Comment by Dineshkarthik** [comment]
@tshrinivasan DB need to be dropped and created again. Made some changes to the Schema.

**Comment by tshrinivasan** [comment]
Got same error even after dropping db and running python3 populate_db.py

**Comment by Dineshkarthik** [comment]
Once the DB is dropped and created new, Please start the user flow with `/start` comment.

**Comment by tshrinivasan** [comment]
it works. thanks.
